version: "3"

services:
  # CONFIG SERVER SERVICE
  configserver:
    build:
      context: ./configserverlocal
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    
  # DISCOVERY SERVICE
  discovery:
    build:
      context: ./lojas-pires-eureka-server
      dockerfile: Dockerfile
    ports:
      - 9091:9091
    environment:
      CONFIGSERVER_URL: http://configserver:8888
    depends_on:
      - configserver


  # API GATEWAY
  gateway:
    build:
      context: ./lojas-pires-zull
      dockerfile: Dockerfile
    ports:
      - 9090:9090
    depends_on:
      - discovery
      - configserver