server:
  port: 9090
  wait-time-in-ms-when-sync-empty: 3000
eureka:
  instance:
    hostname: ${DISCOVERY_URL:localhost}
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
#authserver:
#    hostname: http://localhost:9092
#security:
#    oauth2:
#        client:            
#            scope: password
#        resource:
#            userInfoUri: ${authserver.hostname}/user